import '@/styles/globals.scss'
import { Inter } from 'next/font/google'
import {HomeLogo} from "@/components/header/HomeLogo";
import {AboutButton} from "@/components/header/AboutButton";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomeLogo/>
        <AboutButton/>
        {children}
      </body>
    </html>
  )
}
